### ISSUE TITLE
Why?? main.cpp:43: undefined reference to `setup' collect2.exe: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by IHateNameStealers** [craigg96/vesc_can_bus_arduino#3]
I really hope someone here can help me with this!
Why do I keep getting this error when trying to compile it?

```
C:\Users\Noel\AppData\Local\Temp\ccDXW8xc.ltrans0.ltrans.o: In function `main':
C:\Users\Noel\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/main.cpp:43: undefined reference to `setup'
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Micro.
```

![arduino_vesc_can_error](https://user-images.githubusercontent.com/30197751/202217260-e721114f-6ff3-4672-bfcf-15a44da12df1.jpg)

**Comment by IHateNameStealers** [comment]
I could really use some help with this "error", so if anyone here knows what's going on I would really appreciate it.

**Comment by adrientsmith** [comment]
You have an underscore after ```void setup``` that shouldn't be there.

**Comment by IHateNameStealers** [comment]
Pfffffff.. Found it... It should be **void setup()** and not **void setup_()**
Crazy thing is, that it's a copy/paste from the example provide from here!
See: https://github.com/craigg96/vesc_can_bus_arduino/blob/main/examples/vesc_can_bus.ino

Anyway. Thank you for your help. It's compiling fine now!

**Comment by craigg96** [comment]
Sorry, this typo is fixed now
