### ISSUE TITLE
watt_hours

### ISSUE THREAD

**Issue by IHateNameStealers** [craigg96/vesc_can_bus_arduino#4]
Hi craigg96,

Do you think that it is possible to get the "watt_hours" value too?
If so, what needs to be changed?

Thank you.

**Comment by craigg96** [comment]
watt hours are sent under status 3 for vesc. Can address for this is 80000F0A.


If you add `long WattHours` as a calss variable in the header file next to erpm then add the following to the cpp `spin()` function
```
if (rxId == 0x80000F0A) {
    unsigned char WHvals[4];
    WHvals[0] = rxBuf[3];
    WHvals[1] = rxBuf[2];
    WHvals[2] = rxBuf[1];
    WHvals[3] = rxBuf[0];
    WattHours = *(long *)WHvals;
  }
```
I'll push this change soon

**Comment by craigg96** [comment]
Added the above to master
