### ISSUE TITLE
Other can tranceiver support (esp32 and TJA1050)

### ISSUE THREAD

**Issue by astra404** [craigg96/vesc_can_bus_arduino#5]
Hello,
Is it possible to use different CAN IC with this library? I am planing to use esp32 which has a integrated CAN controller. So only transceiver IC is required.

**Comment by astra404** [comment]
So I've modified the library to use the esp32 can tranceiver.
https://github.com/astra404/VESC_CAN_bus_native_esp32

**Comment by craigg96** [comment]
Great work! 
Thanks
