### ISSUE TITLE
Multiple VESCs

### ISSUE THREAD

**Issue by csicso** [craigg96/vesc_can_bus_arduino#7]
Hi,
I need to control 4 VESCs independently on the same CAN bus, it's ok that I need to set 4 separate CAN ID in the VESC Tool, but how can  I drive them with different RPM / current, etc, and read the telemetry data back knowing which one is sent the data?

**Comment by DerKrawallkeks** [comment]
If you've made any progress, please post

**Comment by csicso** [comment]
> If you've made any progress, please post
Here is a modified code to control different VESC-s:

  uint32_t data_id = 0x000000000;
  data_id = data_id | 1 << 8; //0 - SET_CURRENT command
  data_id = data_id | vesc_id;  
Set the value of the vesc_id variable.

**Comment by DerKrawallkeks** [comment]
Thanks csicso, I've figured it out in the meantime, but thanks for actually coming back to answer!:)

**Comment by craigg96** [comment]
The VESC ID is defined by the last two characters in the hexidecimal address used in the last line of the send functions. 
In this case i've hardcoded '0A' at the end of each vesc_send function which is vesc ID 10. If you add another send function you can pass the value to a different vesc.

For example...
This function sets duty on 'vesc1' on address 10.

```
void CAN::vesc_1_set_duty(float duty) {
  uint32_t set_value = duty * 100000;
  uint8_t buffer[4];
  buffer[0] = (set_value >> 24) & 0xFF;
  buffer[1] = (set_value >> 16) & 0xFF;
  buffer[2] = (set_value  >> 8  )  & 0xFF;
  buffer[3] = set_value & 0xFF;
  byte sndStat = CAN0.sendMsgBuf(0x0000000A, 1, 4, buffer);
}
```

And this function sets duty on vesc 2 (vesc ID 28 i.e. 1C in hex)

```
void CAN::vesc_2_set_duty(float duty) {
  uint32_t set_value = duty * 100000;
  uint8_t buffer[4];
  buffer[0] = (set_value >> 24) & 0xFF;
  buffer[1] = (set_value >> 16) & 0xFF;
  buffer[2] = (set_value  >> 8  )  & 0xFF;
  buffer[3] = set_value & 0xFF;
  byte sndStat = CAN0.sendMsgBuf(0x0000001C, 1, 4, buffer);
}
```

You could also add the vesc ID as an argument then set the address when you call the function. But with one or two vescs i think its simpler to just hardcode the vesc IDs.

Hope this helps

Craig
